name: Project Main Branch Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  example_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: '[unit test] example'
        run: npm test ./__tests__/example.test.js

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: '[unit test] project cards'
        run: npm test ./__tests__/ProjectCard.unit.test.js

  E2E_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: '[E2E test] project cards'
        run: npm test ./__tests__/ProjectCard.E2E.test.js
      - name: '[E2E test] contacts'
        run: npm test ./__tests__/Contacts.E2E.test.js
      - name: '[E2E test] calendar'
        run: npm test ./__tests__/calendar.test.js

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Code Linting
        run: npm run lint

  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS/checkout 
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
