name: Project Main Branch Tests

on: [push]

  Calendar_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install --save-dev puppeteer
      - name: '[calendar test]'
        run: npm test ./__tests__/calendar.test.js
