name: Project Main Branch Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install --save-dev puppeteer jest

      #- name: Linting and Code Style Enforcement
      # run: npm run lint
      #- name: Code Quality Check
      # run: npm run quality-check
      - name: '[unit test] example'
        run: npm test ./__tests__/example.test.js
        # ADD CHECKS TO PACKAGE.JSON FOR FINAL DRAFT
      - name: '[unit test] project cards'
        run: npm test ./__tests__/ProjectCard.unit.test.js
      # - name: '[unit test] Task manager'
      #   run: npm test ./__tests__/project-card.test.js
      - name: '[E2E test] project cards'
        run: npm test ./__tests__/ProjectCard.E2E.test.js --runInBand

  coverage_report:
    name: Generate coverage report
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # ... Generate LCOV files or download it from a different job
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1.0.0
      - name: Report LCOV
        uses: zgosalvez/github-actions-report-lcov@v4.1.8

  code_format:
    name: Lint Action
    uses: wearerequired/lint-action@v2.3.0
            