name: Project Main Branch Tests

on: [push]

jobs:
  example_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install --save-dev puppeteer jest
      - name: '[unit test] example'
        run: npm test ./__tests__/example.test.js

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install --save-dev puppeteer jest
      #- name: '[unit test] project cards'
        #run: npm test ./__tests__/ProjectCard.unit.test.js --runInBand

  E2E_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install --save-dev puppeteer
      #- name: '[E2E test] project cards'
        #run: npm test ./__tests__/ProjectCard.E2E.test.js --runInBand

      - name: '[calendar test]'
        run: npm test ./__tests__/calendar.test.js
        
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Code Linting
        run: npm run lint

  # code_coverage:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@main
  #   - uses: codecov/codecov-action@v4
  #     with:
  #       fail_ci_if_error: true # optional (default = false)
  #       flags: unittests # optional
  #       name: codecov-umbrella # optional
  #       token: ${{ secrets.CODECOV_TOKEN }} # required
  #       verbose: true # optional (default = false)
