name: Project Main Branch Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install --save-dev puppeteer jest 

      #- name: Linting and Code Style Enforcement
      # run: npm run lint
      #- name: Code Quality Check
      # run: npm run quality-check
      - name: '[unit test] example'
        run: npm test ./__tests__/example.test.js
        # ADD CHECKS TO PACKAGE.JSON FOR FINAL DRAFT
      - name: '[unit test] Helper.js'
        run: npm test ./__tests__/Helper.test.js
      # - name: '[unit test] Task manager'
      #   run: npm test ./__tests__/project-card.test.js
      - name: '[E2E test] project cards'
        run: npm test ./__tests__/ProjectCard/ProjectCard.test.js
