name: Project Main Branch Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  example_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node 18
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm install
      - name: '[unit test] example'
        run: npm test ./__tests__/example.test.js
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN  }}

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node 18
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm install
      - name: '[unit test] project cards'
        run: npm test ./__tests__/ProjectCard.unit.test.js
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  E2E_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node 18
        run: npm install
      - name: '[E2E test] project cards'
        run: npm test ./__tests__/ProjectCard.E2E.test.js
      - name: '[E2E test] contacts'
        run: npm test ./__tests__/Contacts.E2E.test.js
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Code Linting
        run: npm run lint
