name: Project Main Branch Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install

      #- name: Linting and Code Style Enforcement
       # run: npm run lint 

      #- name: Code Quality Check
       # run: npm run quality-check 

      - name: Unit Tests
        run: npm test ./tests/example.js
        # ADD CHECKS TO PACKAGE.JSON FOR FINAL DRAFT
